### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by opensource4life** [H4wk507/cda-downloader#11]
Hi I have a problem with downloading one of the series, the script reports an error during resolution selection, log below and a link to an example video that generates the error:

Traceback (most recent call last):
  File "/usr/local/bin/cda-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/cda_dl/main.py", line 110, in main
    Downloader(args)
  File "/usr/local/lib/python3.10/dist-packages/cda_dl/downloader.py", line 66, in __init__
    asyncio.run(self.main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/cda_dl/downloader.py", line 85, in main
    await self.download_videos(session)
  File "/usr/local/lib/python3.10/dist-packages/cda_dl/downloader.py", line 208, in download_videos
    await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.10/dist-packages/cda_dl/downloader.py", line 200, in wrapper
    await Video(video_url, session, self.ui).download_video(
  File "/usr/local/lib/python3.10/dist-packages/cda_dl/video.py", line 80, in download_video
    await self.initialize(download_options)
  File "/usr/local/lib/python3.10/dist-packages/cda_dl/video.py", line 113, in initialize
    self.resolution = self.get_adjusted_resolution(download_options)
  File "/usr/local/lib/python3.10/dist-packages/cda_dl/video.py", line 233, in get_adjusted_resolution
    self.get_best_resolution()
  File "/usr/local/lib/python3.10/dist-packages/cda_dl/video.py", line 224, in get_best_resolution
    return f"{max(int(k[:-1]) for k in self.resolutions.keys())}p"
  File "/usr/local/lib/python3.10/dist-packages/cda_dl/video.py", line 224, in <genexpr>
    return f"{max(int(k[:-1]) for k in self.resolutions.keys())}p"
ValueError: invalid literal for int() with base 10: 'aut'

Example link: https://www.cda.pl/video/117520048a/vfilm

**Comment by H4wk507** [comment]
Hi @opensource4life. Thanks for raising an issue. Unfortunately I was not able to reproduce the bug, because I no longer have the cda premium account. Is this bug only occuring for premium videos? You can always select best resolution manually by using the `-r` option.

**Comment by opensource4life** [comment]
Yeah, this error occurs for every premium video, If you specify the resolution manually using the for example "-r 1080p" you will get the following error:

Traceback (most recent call last):
  File "/usr/local/bin/cda-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/cda_dl/main.py", line 110, in main
    Downloader(args)
  File "/usr/local/lib/python3.10/dist-packages/cda_dl/downloader.py", line 66, in __init__
    asyncio.run(self.main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/cda_dl/downloader.py", line 85, in main
    await self.download_videos(session)
  File "/usr/local/lib/python3.10/dist-packages/cda_dl/downloader.py", line 208, in download_videos
    await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.10/dist-packages/cda_dl/downloader.py", line 200, in wrapper
    await Video(video_url, session, self.ui).download_video(
  File "/usr/local/lib/python3.10/dist-packages/cda_dl/video.py", line 80, in download_video
    await self.initialize(download_options)
  File "/usr/local/lib/python3.10/dist-packages/cda_dl/video.py", line 136, in initialize
    self.video_stream = await self.get_video_stream()
  File "/usr/local/lib/python3.10/dist-packages/cda_dl/video.py", line 260, in get_video_stream
    video_stream = await get_request(self.file, self.session, self.headers)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/asyncio/__init__.py", line 189, in async_wrapped
    return await copy(fn, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/asyncio/__init__.py", line 111, in __call__
    do = await self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/dist-packages/tenacity/asyncio/__init__.py", line 114, in __call__
    result = await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/cda_dl/utils.py", line 131, in get_request
    response = await session.get(url, headers=headers)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 586, in _request
    raise err_exc_cls(url)
aiohttp.client_exceptions.InvalidUrlClientError: not%20allowed


Listing resolution with -R parameter works correctly.

**Comment by rupertst** [comment]
The same error, when try to download from cda premium. Python 3.12
aiohttp.client_exceptions.InvalidUrlClientError: not%20allowed
;-(
No matter if I set resolution manualy or not
